//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationStudioGarment.manager
{
    using System;
    using System.Collections.Generic;
    
    public partial class BASKET
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BASKET()
        {
            this.ORDERs = new HashSet<ORDER>();
        }
    
        public long id_basket { get; set; }
        public long count { get; set; }
        public Nullable<long> id_client { get; set; }
        public Nullable<long> id_product { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual CLIENT CLIENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER> ORDERs { get; set; }
    }
}
