//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationStudioGarment.manager
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER
    {
        public long id_order { get; set; }
        public string order_date { get; set; }
        public string order_time { get; set; }
        public long order_status { get; set; }
        public decimal total_sum { get; set; }
        public Nullable<long> id_basket { get; set; }
    
        public virtual BASKET BASKET { get; set; }
    }
}
