//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationStudioGarment.manager
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER
    {
        public int id_order { get; set; }
        public string order_date { get; set; }
        public string order_time { get; set; }
        public int order_status { get; set; }
        public decimal total_sum { get; set; }
        public int id_basket { get; set; }
    
        public virtual BASKET BASKET { get; set; }
    }
}
