//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationStudioGarment.manager
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT_STRUCTURE
    {
        public long id_product_structure { get; set; }
        public long count { get; set; }
        public Nullable<long> id_product { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
