//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationStudioGarment_WinForm.manager
{
    using System;
    using System.Collections.Generic;
    
    public partial class BASKET
    {
        public int id_basket { get; set; }
        public int count { get; set; }
        public int id_client { get; set; }
        public int id_product { get; set; }
        public int id_order { get; set; }
    
        public virtual ORDER ORDER { private get; set; }
        public virtual PRODUCT PRODUCT { private get; set; }
        public virtual CLIENT CLIENT { private get; set; }
    }
}
